steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaBuildTool: classic
    mtaJarLocation: '/opt/sap/mta.jar'
  neoDeploy:
    neoHome: '/opt/sap/neo-sdk/'
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'k1og0f63bw'
      host: 'hana.ondemand.com'