steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '~/workspace/PSDevOpsDemo_master/mta.jar'
  neoDeploy:
    neoHome: '~/workspace/PSDevOpsDemo_master/neo-sdk/'
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'k1og0f63bw'
      host: 'hana.ondemand.com'